services:
    landingpage:
        build: .
        container_name: landingpage
        restart: unless-stopped
        env_file: .env
        networks:
            - web
networks:
    web:
        external: true
